"""empty message

Revision ID: 04a02025651a
Revises: fb5012cf8c2d
Create Date: 2024-05-16 11:19:30.875253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a02025651a'
down_revision = 'fb5012cf8c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('streetNumber', sa.String(length=64), nullable=False),
    sa.Column('street', sa.String(length=64), nullable=False),
    sa.Column('suburb', sa.String(length=64), nullable=False),
    sa.Column('postcode', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('datetimeCreated', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_request_datetimeCreated'), ['datetimeCreated'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_job'), ['job'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_postcode'), ['postcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_street'), ['street'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_streetNumber'), ['streetNumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_suburb'), ['suburb'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_user_id'), ['user_id'], unique=False)

    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeEstimate', sa.Float(), nullable=False),
    sa.Column('dateOffered', sa.Date(), nullable=False),
    sa.Column('jobRequest_id', sa.Integer(), nullable=False),
    sa.Column('tradie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jobRequest_id'], ['job_request.id'], ),
    sa.ForeignKeyConstraint(['tradie_id'], ['tradie_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_offer_dateOffered'), ['dateOffered'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_offer_jobRequest_id'), ['jobRequest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_offer_tradie_id'), ['tradie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_offer_tradie_id'))
        batch_op.drop_index(batch_op.f('ix_job_offer_jobRequest_id'))
        batch_op.drop_index(batch_op.f('ix_job_offer_dateOffered'))

    op.drop_table('job_offer')
    with op.batch_alter_table('job_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_request_suburb'))
        batch_op.drop_index(batch_op.f('ix_job_request_streetNumber'))
        batch_op.drop_index(batch_op.f('ix_job_request_street'))
        batch_op.drop_index(batch_op.f('ix_job_request_state'))
        batch_op.drop_index(batch_op.f('ix_job_request_postcode'))
        batch_op.drop_index(batch_op.f('ix_job_request_job'))
        batch_op.drop_index(batch_op.f('ix_job_request_description'))
        batch_op.drop_index(batch_op.f('ix_job_request_datetimeCreated'))

    op.drop_table('job_request')
    op.drop_table('image')
    # ### end Alembic commands ###
