"""empty message

Revision ID: 0fe5e638d8da
Revises: 33e363be3ce6
Create Date: 2024-05-18 09:31:30.962442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe5e638d8da'
down_revision = '33e363be3ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejectedStatus', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_column('rejectedStatus')

    # ### end Alembic commands ###
