"""empty message

Revision ID: 6e79b430868b
Revises: 04a02025651a
Create Date: 2024-05-16 14:15:03.221439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e79b430868b'
down_revision = '04a02025651a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tradeRequired', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_job_request_tradeRequired'), ['tradeRequired'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_request_tradeRequired'))
        batch_op.drop_column('tradeRequired')

    # ### end Alembic commands ###
