"""TradieUser class

Revision ID: fb5012cf8c2d
Revises: 65ae930c178c
Create Date: 2024-04-26 13:40:15.950741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5012cf8c2d'
down_revision = '65ae930c178c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradie_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade', sa.String(length=64), nullable=False),
    sa.Column('hourlyRate', sa.Float(), nullable=False),
    sa.Column('calloutFee', sa.Float(), nullable=False),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tradie_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tradie_user_trade'), ['trade'], unique=False)
        batch_op.create_index(batch_op.f('ix_tradie_user_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradie_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tradie_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_tradie_user_trade'))

    op.drop_table('tradie_user')
    # ### end Alembic commands ###
